Repository go-vela/vela-kaniko, pull requests merged in 2020-01, with the labels that each got.

#5 refactor: move plugin logic to separate files
  cmd/vela-docker/main.go
  cmd/vela-docker/plugin.go
  cmd/vela-docker/validate.go
Labels: enhancement

#6 feat: add build struct for plugin
  .gitignore
  cmd/vela-docker/build.go
  cmd/vela-docker/build_test.go
Labels: feature

#7 feat: add registry struct for plugin
  cmd/vela-docker/registry.go
  cmd/vela-docker/registry_test.go
Labels: feature

#8 feat: add image struct for plugin
  cmd/vela-docker/image.go
  cmd/vela-docker/image_test.go
Labels: feature

#9 feat: add repo struct for plugin
  cmd/vela-docker/image.go
  cmd/vela-docker/repo.go
  cmd/vela-docker/repo_test.go
Labels: feature

#10 feat: add plugin struct
  cmd/vela-docker/plugin.go
  cmd/vela-docker/plugin_test.go
Labels: feature

#11 feat: add write method for registry
  cmd/vela-docker/plugin.go
  cmd/vela-docker/registry.go
  cmd/vela-docker/registry_test.go
  go.mod
  go.sum
Labels: feature

#12 feat: add exec method for plugin
  cmd/vela-docker/plugin.go
  cmd/vela-docker/plugin_test.go
Labels: feature

#13 refactor: add extra information for plugin
  cmd/vela-docker/main.go
  cmd/vela-docker/plugin.go
  cmd/vela-docker/validate.go
Labels: enhancement

#14 chore: add copyright notice to plugin files
  cmd/vela-docker/build.go
  cmd/vela-docker/build_test.go
  cmd/vela-docker/image.go
  cmd/vela-docker/image_test.go
  cmd/vela-docker/plugin.go
  cmd/vela-docker/plugin_test.go
  cmd/vela-docker/registry.go
  cmd/vela-docker/registry_test.go
  cmd/vela-docker/repo.go
  cmd/vela-docker/repo_test.go
Labels: enhancement

#15 refactor: make flags method on plugin struct
  cmd/vela-docker/plugin.go
  cmd/vela-docker/plugin_test.go
Labels: enhancement

#16 feat: add exec method for plugin struct
  cmd/vela-docker/command.go
  cmd/vela-docker/command_test.go
  cmd/vela-docker/plugin.go
  cmd/vela-docker/plugin_test.go
Labels: feature

#17 feat: add certs from alpine
  Dockerfile
Labels: feature

#18 docs: add plugin usage docs
  .github/README.md
  DOCS.md
Labels: enhancement

#19 feat: add plugin template
  .vela/template.yml
Labels: feature

#20 feat: enable loading config from env file
  cmd/vela-docker/main.go
  go.mod
  go.sum
Labels: feature

#21 chore: add debug and trace logs
  cmd/vela-docker/plugin.go
  cmd/vela-docker/registry.go
Labels: enhancement

#22 docs: add comments for code
  cmd/vela-docker/build.go
  cmd/vela-docker/image.go
  cmd/vela-docker/plugin.go
  cmd/vela-docker/registry.go
  cmd/vela-docker/repo.go
Labels: enhancement

#23 fix: update syntax for makefile
  Dockerfile.example
  Makefile
Labels: bug

#24 chore: update copyright for 2020
  .github/README.md
  .vela/template.yml
  Dockerfile
  Makefile
  cmd/vela-docker/build.go
  cmd/vela-docker/build_test.go
  cmd/vela-docker/command.go
  cmd/vela-docker/command_test.go
  cmd/vela-docker/image.go
  cmd/vela-docker/image_test.go
  cmd/vela-docker/main.go
  cmd/vela-docker/plugin.go
  cmd/vela-docker/plugin_test.go
  cmd/vela-docker/registry.go
  cmd/vela-docker/registry_test.go
  cmd/vela-docker/repo.go
  cmd/vela-docker/repo_test.go
Labels: enhancement

#25 chore: use full apache license
  LICENSE
Labels: enhancement

#26 improvement: add log entry with metadata
  cmd/vela-docker/main.go
Labels: enhancement

#27 chore: update to latest kaniko version
  Dockerfile
Labels: enhancement
