Repository go-vela/vela-kaniko, pull requests merged in 2020-06, with the labels that each got.

#48 revert: repo issue template
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/not_here.md
Labels: enhancement

#49 chore: update to latest version of kaniko
  Dockerfile
Labels: dependencies

#50 feat: add reviewdog with golangci-lint
  .github/workflows/reviewdog.yml
Labels: feature
